=== kelven939/XMLexercise/Schemas/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="linha" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:positiveInteger"/>
              <xs:element name="Nome" type="xs:string"/>
              <xs:element name="Estrelas">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="5"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Area">
                <xs:simpleType>
                  <xs:list itemType="xs:string"/>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Endereco" type="xs:string"/>
              <xs:element name="Distancia" type="xs:decimal" minOccurs="0"/>
              <xs:element name="Disponibilidade">
                <xs:simpleType>
                  <xs:restriction base="xs:boolean"/>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== kelven939/XMLexercise/Schemas/instancia.xml
<dados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="schema.xsd">
  <linha>
    <ID>1</ID>
    <Nome>Tivoli</Nome>
    <Estrelas>2</Estrelas>
    <Area>Internet</Area>
    <Endereco>Beira</Endereco>
    <Distancia>0.2</Distancia>
    <Disponibilidade>true</Disponibilidade>
  </linha>
  <linha>
    <ID>2</ID>
    <Nome>Mocambique</Nome>
    <Estrelas>4</Estrelas>
    <Area>Ginasio</Area>
    <Endereco>Baixa</Endereco>
    <Disponibilidade>false</Disponibilidade>
  </linha>
  <linha>
    <ID>3</ID>
    <Nome>Sena</Nome>
    <Estrelas>5</Estrelas>
    <Area>Restaurante</Area>
    <Endereco>Macuti</Endereco>
    <Disponibilidade>false</Disponibilidade>
  </linha>
  <linha>
    <ID>4</ID>
    <Nome>Vip</Nome>
    <Estrelas>3</Estrelas>
    <Area>Parqueamento</Area>
    <Endereco>Chaimite</Endereco>
    <Distancia>0.6</Distancia>
    <Disponibilidade>true</Disponibilidade>
  </linha>
</dados>
